lib/payroll_web/router.ex
defmodule PayrollWeb.Router do
  use PayrollWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {PayrollWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", PayrollWeb do
    pipe_through :browser

    get "/", CompanyController, :index
  end

  scope "/company", PayrollWeb do
    pipe_through :browser

    get "/new", CompanyController, :new
    get "/:id", CompanyController, :show
    get "/:id/edit", CompanyController, :edit
    put "/:id", CompanyController, :update
    delete "/:id", CompanyController, :delete
    post "/create", CompanyController, :create
  end

  scope "/employee", PayrollWeb do
    pipe_through :browser

    get "/", EmployeeController, :index
    get "/new", EmployeeController, :new
    get "/:id", EmployeeController, :show
    get "/:id/edit", EmployeeController, :edit
    put "/:id", EmployeeController, :update
    delete "/:id", EmployeeController, :delete
    post "/create", EmployeeController, :create

  end

  # Other scopes may use custom stacks.
  # scope "/api", PayrollWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: PayrollWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/payroll/app/employee.ex
defmodule Payroll.App.Employee do
  use Ecto.Schema
  import Ecto.Changeset

  schema "employees" do
    field :age, :integer
    field :name, :string
    field :profession, :string
    field :salary, :decimal
    field :sex, :string
    belongs_to :company, Payroll.App.Company

    timestamps()
  end

  @doc false
  def changeset(employee, attrs) do
    employee
    |> cast(attrs, [:name, :age, :sex, :profession, :salary, :company_id])
    |> validate_required([:name, :age, :sex, :profession, :salary, :company_id])
  end

end

lib/payroll_web/controllers/employee_controller.ex
defmodule PayrollWeb.EmployeeController do
  use PayrollWeb, :controller

  alias Payroll.App
  alias Payroll.App.Employee

  def index(conn, params) do
    if Map.has_key?(params, "company") do
      %{"company" => company_id} = params
      employees = App.list_employees_by_company(company_id)
      render(conn, "index.html", employees: employees)
    else
      employees = App.list_employees()
      gender = App.count_employees_by_gender
      professions = App.count_employees_by_profession
      render(conn, "all.html", employees: employees, gender: gender, professions: professions)
    end
  end

  def new(conn, _params) do
    changeset = App.change_employee(%Employee{})
    companies = for company <- App.list_companies do [value: company.id, key: company.name] end
    render(conn, "new.html", changeset: changeset, companies: companies)
  end

  def create(conn, %{"employee" => employee_params}) do
    case App.create_employee(employee_params) do
      {:ok, employee} ->
        conn
        |> put_flash(:info, "Employee created successfully.")
        |> redirect(to: Routes.employee_path(conn, :show, employee))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    employee = App.get_employee!(id)
    render(conn, "show.html", employee: employee)
  end

  def edit(conn, %{"id" => id}) do
    employee = App.get_employee!(id)
    changeset = App.change_employee(employee)
    companies = for company <- App.list_companies do [value: company.id, key: company.name] end
    render(conn, "edit.html", employee: employee, changeset: changeset, companies: companies)
  end

  def update(conn, %{"id" => id, "employee" => employee_params}) do
    employee = App.get_employee!(id)

    case App.update_employee(employee, employee_params) do
      {:ok, employee} ->
        conn
        |> put_flash(:info, "Employee updated successfully.")
        |> redirect(to: Routes.employee_path(conn, :show, employee))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", employee: employee, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    employee = App.get_employee!(id)
    {:ok, _employee} = App.delete_employee(employee)

    conn
    |> put_flash(:info, "Employee deleted successfully.")
    |> redirect(to: Routes.employee_path(conn, :index))
  end
end

lib/payroll_web/views/employee_view.ex
defmodule PayrollWeb.EmployeeView do
  use PayrollWeb, :view
end

lib/payroll_web/templates/employee/index.html.heex
<h1>Listing Employees</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Profession</th>
      <th>Salary</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for employee <- @employees do %>
    <tr>
      <td><%= employee.name %></td>
      <td><%= employee.age %></td>
      <td><%= employee.sex %></td>
      <td><%= employee.profession %></td>
      <td><%= employee.salary %></td>

      <td>
        <span><%= button "Edit", class: "btn blue", method: "get", to: Routes.employee_path(@conn, :edit, employee) %></span>
        <span><%= button "Delete", class: "btn red", to: Routes.employee_path(@conn, :delete, employee), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<div style="margin-top: 10px">
  <%= button "Back", to: Routes.company_path(@conn, :index), method: "get", class: "btn grey" %>
  <%= button "New Employee", method: "get", class: "btn", to: Routes.employee_path(@conn, :new) %>
</div>

lib/payroll_web/templates/employee/show.html.heex
<h1>Show Employee</h1>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @employee.name %>
  </li>

  <li>
    <strong>Age:</strong>
    <%= @employee.age %>
  </li>

  <li>
    <strong>Sex:</strong>
    <%= @employee.sex %>
  </li>

  <li>
    <strong>Profession:</strong>
    <%= @employee.profession %>
  </li>

  <li>
    <strong>Salary:</strong>
    <%= @employee.salary %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.employee_path(@conn, :edit, @employee) %></span> |
<span><%= link "Back", to: Routes.employee_path(@conn, :index) %></span>